spring:
  application:
    name: Ergasia

  datasource:
    url: jdbc:h2:file:./LOCAL_DATA/h2/ergasia;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE
    username: taxiarchis
    password: taxkoul24
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect
      hibernate.format_sql: true

noc:
  api:
    url: "http://localhost:8080/api/v1"

app:
  jwt:
    issuer: "ergasia-api"
    audience: "frontend-client"
    secret: "c3VwZXJzZWNyZXRrZXlfMzJfYnl0ZXNfbG9uZ19mb3Jfam90"
    ttl-minutes: 60
